defmodule OpenDriveWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :open_drive

  @max_request_body_length OpenDrive.Drive.backend_upload_fallback_size()
  require Logger

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_open_drive_key",
    signing_salt: "MQDs9ssr",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :open_drive,
    gzip: not code_reloading?,
    only: OpenDriveWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug :safe_code_reloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :open_drive
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug OpenDriveWeb.UploadParsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: @max_request_body_length,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug OpenDriveWeb.Router

  def safe_code_reloader_init(opts) do
    opts
    |> Keyword.put_new(:server, Phoenix.CodeReloader.Server)
    |> Phoenix.CodeReloader.init()
  end

  def safe_code_reloader(conn, opts) do
    if Process.whereis(opts[:server]) do
      Phoenix.CodeReloader.call(conn, opts)
    else
      Logger.warning(
        "Phoenix.CodeReloader.Server is not running; skipping code reload for this request"
      )

      conn
    end
  end
end
